---
title: "CV summary statistics"
author: "Pascale"
date: "3/17/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## investigate CV data

```{r, echo=FALSE}
library(tidyverse)
library(vegan)
library(cluster)
library(pvclust)
library(pastecs)
library(reshape)
```

# load data from CV_master
```{r}
chip.dat<-read.csv("masterCV_chip.csv")
ben.dat<-read.csv("masterCV_benicia.csv")

head(chip.dat)
head(ben.dat)
```

## calc CV

```{r pressure, echo=FALSE}
#Delta2013-043 has a very large travel time

CV_chip.tt <- chip.dat %>%
  filter(FishID !="Delta2013-043") %>%
  group_by(wateryear, Route, Release_Group_SAIL, Run, add=TRUE) %>%
  summarize(count = n(),
            mean = mean(travel_time, na.rm=TRUE),
            SD = sd(travel_time, na.rm=TRUE))%>%
  mutate(CV=SD/mean)

head(CV_chip.tt)

CV_chip.tt_v2 <- chip.dat %>%
  filter(FishID !="Delta2013-043") %>%
  group_by(wateryear, Route, Release_Group_SAIL, add=TRUE) %>%
  summarize(count = n(),
            mean = mean(travel_time, na.rm=TRUE),
            SD = sd(travel_time, na.rm=TRUE))%>%
  mutate(CV=SD/mean)

head(CV_chip.tt_v2)

write.csv(CV_chip.tt_v2, "CV.Chipps_results.csv")

CV_ben.tt_v2 <- ben.dat %>%
  filter(FishID !="Delta2013-043") %>%
  group_by(wateryear, Route, Release_Group_SAIL, add=TRUE) %>%
  summarize(count = n(),
            mean = mean(travel_time, na.rm=TRUE),
            SD = sd(travel_time, na.rm=TRUE))%>%
  mutate(CV=SD/mean)

head(CV_ben.tt_v2)

write.csv(CV_ben.tt_v2, "CV.Benicia_results.csv")
```

```{r}
dim(chip.dat[duplicated(chip.dat$FishID),])[1]
```

```{r}
max(CV_chip.tt$CV, na.rm=TRUE)
min(CV_chip.tt$CV, na.rm=TRUE)

max(CV_chip.tt$count, na.rm=TRUE)
min(CV_chip.tt$count, na.rm=TRUE)

summary(CV_chip.tt)

hist(CV_chip.tt$CV)
hist(CV_ben.tt_v2$CV)

stat.desc(CV_chip.tt)
```

# boxplots as an alternative to heatmaps

```{r, fig.width=14, fig.height=12}
CV_chip.tt$wateryear<-as.character(CV_chip.tt$wateryear)

ggplot(CV_chip.tt, aes(Route, CV)) +
  geom_boxplot(colour = "grey50") +
  geom_point(aes(col=wateryear)) +
  facet_wrap(~ Release_Group_SAIL)+ theme_minimal()
```

```{r, fig.width=14, fig.height=12}
ggplot(CV_chip.tt, aes(Route, CV)) +
  geom_boxplot(colour = "grey50") +
  geom_point(aes(col=Run)) +
  facet_wrap(~ Release_Group_SAIL)+ theme_minimal()
```

```{r, fig.width=14, fig.height=12}
plot.cv<-ggplot(CV_chip.tt, 
       aes(x=Route, y=wateryear, 
           size = CV, color=Run)) +
    geom_point()+
  facet_wrap(~ Release_Group_SAIL)+ theme_minimal()

plot.cv + geom_jitter(width = 0.5)
```

```{r, fig.width=14, fig.height=12}
ggplot(chip.dat, aes(Route, travel_time)) +
  geom_boxplot(colour = "grey50") +
  geom_point(aes(col=Run)) +
  ylim(0, 100)+
  facet_wrap(~ Release_Group_SAIL)+ theme_minimal()

ggplot(chip.dat, aes(Route, travel_time)) +
  geom_boxplot(colour = "grey50") +
  geom_point(aes(col=wateryear, shape=Run)) +
  ylim(0, 100)+
  facet_wrap(~ Release_Group_SAIL)+ theme_minimal()
```

```{r, fig.width=14, fig.height=12}
plot4ted<-ggplot(chip.dat, aes(Route, travel_time)) +
  geom_boxplot(colour = "red") +
  geom_point(aes(col=wateryear, shape=Run)) +
  ylim(0, 100)+
  facet_wrap(~ Release_Group_SAIL)+ theme_minimal()

plot4ted + geom_jitter(aes(col=wateryear, shape=Run))

# travel times greater than 100 excluded (just Delta2013-043)
```

# anova

```{r}
head(CV_chip.tt_v2)
head(CV_ben.tt_v2)

aov.wy<-aov(CV~wateryear, data = CV_chip.tt_v2)
summary(aov.wy) # not sign = 0.769
aov.rt<-aov(CV~Route, data = CV_chip.tt_v2)
summary(aov.rt) # almost sign = 0.0709
aov.rel<-aov(CV~Release_Group_SAIL, data = CV_chip.tt_v2)
summary(aov.rel) # not sign = 0.342

TukeyHSD(aov.rt)

aov.wy<-aov(CV~wateryear, data = CV_ben.tt_v2)
summary(aov.wy) # not sign = 0.424
aov.rt<-aov(CV~Route, data = CV_ben.tt_v2)
summary(aov.rt) # almost sign = 0.27
aov.rel<-aov(CV~Release_Group_SAIL, data = CV_ben.tt_v2)
summary(aov.rel) # not sign = 0.605

```

