---
title: "Inventory"
author: "Pascale"
date: "3/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Please link all files added to this repository here with a breif description and category:

- Study Summaries
- [Map](Tracy's_ShinyApp.R)
- [CV Data](CV_master.html) 
- [CV Data diagnositcs](CV_summary_stats.html)
- CV Analysis
- [DFA Data](DFA_dataorg_distmatrix.R)
- DFA Anlysis

The "CV Data" file is the code for the assembly of final datasets, which combined Tracy's travel time estimates into single files (depending on final detection location), calculated final salmon-day of detection and includes CV plots.

The "CV Data diagnositcs" file is a continuation of the CV data with plots and summary statsitcs of the dataset created in "CV Data".

The "Map" flie is Tracy's shinyApp of release and reciever locations by year and tag type. Source studies have been added and will be updated. The most recent version is in CHNTelemetrySynth.R and at https://deltascience.shinyapps.io/CHNTelemetrySynth/

The "DFA Data" file is Tracy's organization of the detection data into individual time series for the DFA analysis with edits from Cyril to account for (1) receivers that are too close together, and (2) distance matrix issues.

- removing a couple YBUS receiver sites that didn't seem to be contributing important data
- switched the detection files to the newest, best, filtered files
  